spring:
  application:
    name: crypto-wallet-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5433/cryptowallet
    driver-class-name: org.postgresql.Driver
    username: cryptouser
    password: crypto123
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

crypto:
  bitcoin:
    network: test
  tron:
    api-url: https://api.trongrid.io
    private-key: ${TRON_PRIVATE_KEY:}
  
logging:
  level:
    com.cryptowallet: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE